spring.application.name=catapi
thecatapi.base-url=${THECATAPI_BASE_URL}
thecatapi.api-key=${THECATAPIAPI_KEY}
jwt.secret-key=${SECRET_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/jean
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
